// Code generated by protoc-gen-go. DO NOT EDIT.
// source: child.proto

package proto_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GoodsResponse struct {
	Data                 []*Goods `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsResponse) Reset()         { *m = GoodsResponse{} }
func (m *GoodsResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsResponse) ProtoMessage()    {}
func (*GoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{0}
}

func (m *GoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsResponse.Unmarshal(m, b)
}
func (m *GoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsResponse.Marshal(b, m, deterministic)
}
func (m *GoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsResponse.Merge(m, src)
}
func (m *GoodsResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsResponse.Size(m)
}
func (m *GoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsResponse proto.InternalMessageInfo

func (m *GoodsResponse) GetData() []*Goods {
	if m != nil {
		return m.Data
	}
	return nil
}

type GoodsRequest struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsRequest) Reset()         { *m = GoodsRequest{} }
func (m *GoodsRequest) String() string { return proto.CompactTextString(m) }
func (*GoodsRequest) ProtoMessage()    {}
func (*GoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{1}
}

func (m *GoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsRequest.Unmarshal(m, b)
}
func (m *GoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsRequest.Marshal(b, m, deterministic)
}
func (m *GoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsRequest.Merge(m, src)
}
func (m *GoodsRequest) XXX_Size() int {
	return xxx_messageInfo_GoodsRequest.Size(m)
}
func (m *GoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsRequest proto.InternalMessageInfo

func (m *GoodsRequest) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type ZoneRequest struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneRequest) Reset()         { *m = ZoneRequest{} }
func (m *ZoneRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneRequest) ProtoMessage()    {}
func (*ZoneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{2}
}

func (m *ZoneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneRequest.Unmarshal(m, b)
}
func (m *ZoneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneRequest.Marshal(b, m, deterministic)
}
func (m *ZoneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneRequest.Merge(m, src)
}
func (m *ZoneRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneRequest.Size(m)
}
func (m *ZoneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneRequest proto.InternalMessageInfo

func (m *ZoneRequest) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type ZoneResponse struct {
	Data                 []*Zone  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneResponse) Reset()         { *m = ZoneResponse{} }
func (m *ZoneResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneResponse) ProtoMessage()    {}
func (*ZoneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{3}
}

func (m *ZoneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneResponse.Unmarshal(m, b)
}
func (m *ZoneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneResponse.Marshal(b, m, deterministic)
}
func (m *ZoneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneResponse.Merge(m, src)
}
func (m *ZoneResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneResponse.Size(m)
}
func (m *ZoneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneResponse proto.InternalMessageInfo

func (m *ZoneResponse) GetData() []*Zone {
	if m != nil {
		return m.Data
	}
	return nil
}

type Goods struct {
	GoodsId              int32    `protobuf:"varint,1,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,2,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Goods) Reset()         { *m = Goods{} }
func (m *Goods) String() string { return proto.CompactTextString(m) }
func (*Goods) ProtoMessage()    {}
func (*Goods) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{4}
}

func (m *Goods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Goods.Unmarshal(m, b)
}
func (m *Goods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Goods.Marshal(b, m, deterministic)
}
func (m *Goods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Goods.Merge(m, src)
}
func (m *Goods) XXX_Size() int {
	return xxx_messageInfo_Goods.Size(m)
}
func (m *Goods) XXX_DiscardUnknown() {
	xxx_messageInfo_Goods.DiscardUnknown(m)
}

var xxx_messageInfo_Goods proto.InternalMessageInfo

func (m *Goods) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *Goods) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

type Zone struct {
	ZoneId               int32    `protobuf:"varint,1,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	ZoneName             string   `protobuf:"bytes,2,opt,name=zoneName,proto3" json:"zoneName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Zone) Reset()         { *m = Zone{} }
func (m *Zone) String() string { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()    {}
func (*Zone) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{5}
}

func (m *Zone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Zone.Unmarshal(m, b)
}
func (m *Zone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Zone.Marshal(b, m, deterministic)
}
func (m *Zone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Zone.Merge(m, src)
}
func (m *Zone) XXX_Size() int {
	return xxx_messageInfo_Zone.Size(m)
}
func (m *Zone) XXX_DiscardUnknown() {
	xxx_messageInfo_Zone.DiscardUnknown(m)
}

var xxx_messageInfo_Zone proto.InternalMessageInfo

func (m *Zone) GetZoneId() int32 {
	if m != nil {
		return m.ZoneId
	}
	return 0
}

func (m *Zone) GetZoneName() string {
	if m != nil {
		return m.ZoneName
	}
	return ""
}

type ItemResponse struct {
	Data                 []*Item  `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemResponse) Reset()         { *m = ItemResponse{} }
func (m *ItemResponse) String() string { return proto.CompactTextString(m) }
func (*ItemResponse) ProtoMessage()    {}
func (*ItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{6}
}

func (m *ItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemResponse.Unmarshal(m, b)
}
func (m *ItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemResponse.Marshal(b, m, deterministic)
}
func (m *ItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemResponse.Merge(m, src)
}
func (m *ItemResponse) XXX_Size() int {
	return xxx_messageInfo_ItemResponse.Size(m)
}
func (m *ItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemResponse proto.InternalMessageInfo

func (m *ItemResponse) GetData() []*Item {
	if m != nil {
		return m.Data
	}
	return nil
}

type ItemRequest struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemRequest) Reset()         { *m = ItemRequest{} }
func (m *ItemRequest) String() string { return proto.CompactTextString(m) }
func (*ItemRequest) ProtoMessage()    {}
func (*ItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{7}
}

func (m *ItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemRequest.Unmarshal(m, b)
}
func (m *ItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemRequest.Marshal(b, m, deterministic)
}
func (m *ItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemRequest.Merge(m, src)
}
func (m *ItemRequest) XXX_Size() int {
	return xxx_messageInfo_ItemRequest.Size(m)
}
func (m *ItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemRequest proto.InternalMessageInfo

func (m *ItemRequest) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type Item struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{8}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type User struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Nick                 string   `protobuf:"bytes,3,opt,name=nick,proto3" json:"nick,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{9}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *User) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	Data                 *User    `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{10}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetData() *User {
	if m != nil {
		return m.Data
	}
	return nil
}

type UserRequest struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	UserId               int64    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{11}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *UserRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type ButtonAddRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ButtonAddRequest) Reset()         { *m = ButtonAddRequest{} }
func (m *ButtonAddRequest) String() string { return proto.CompactTextString(m) }
func (*ButtonAddRequest) ProtoMessage()    {}
func (*ButtonAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{12}
}

func (m *ButtonAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ButtonAddRequest.Unmarshal(m, b)
}
func (m *ButtonAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ButtonAddRequest.Marshal(b, m, deterministic)
}
func (m *ButtonAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ButtonAddRequest.Merge(m, src)
}
func (m *ButtonAddRequest) XXX_Size() int {
	return xxx_messageInfo_ButtonAddRequest.Size(m)
}
func (m *ButtonAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ButtonAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ButtonAddRequest proto.InternalMessageInfo

func (m *ButtonAddRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ButtonAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ButtonDelRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ButtonDelRequest) Reset()         { *m = ButtonDelRequest{} }
func (m *ButtonDelRequest) String() string { return proto.CompactTextString(m) }
func (*ButtonDelRequest) ProtoMessage()    {}
func (*ButtonDelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{13}
}

func (m *ButtonDelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ButtonDelRequest.Unmarshal(m, b)
}
func (m *ButtonDelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ButtonDelRequest.Marshal(b, m, deterministic)
}
func (m *ButtonDelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ButtonDelRequest.Merge(m, src)
}
func (m *ButtonDelRequest) XXX_Size() int {
	return xxx_messageInfo_ButtonDelRequest.Size(m)
}
func (m *ButtonDelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ButtonDelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ButtonDelRequest proto.InternalMessageInfo

func (m *ButtonDelRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BoolResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BoolResponse) Reset()         { *m = BoolResponse{} }
func (m *BoolResponse) String() string { return proto.CompactTextString(m) }
func (*BoolResponse) ProtoMessage()    {}
func (*BoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{14}
}

func (m *BoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BoolResponse.Unmarshal(m, b)
}
func (m *BoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BoolResponse.Marshal(b, m, deterministic)
}
func (m *BoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BoolResponse.Merge(m, src)
}
func (m *BoolResponse) XXX_Size() int {
	return xxx_messageInfo_BoolResponse.Size(m)
}
func (m *BoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BoolResponse proto.InternalMessageInfo

func (m *BoolResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CpsAddRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpsAddRequest) Reset()         { *m = CpsAddRequest{} }
func (m *CpsAddRequest) String() string { return proto.CompactTextString(m) }
func (*CpsAddRequest) ProtoMessage()    {}
func (*CpsAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{15}
}

func (m *CpsAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpsAddRequest.Unmarshal(m, b)
}
func (m *CpsAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpsAddRequest.Marshal(b, m, deterministic)
}
func (m *CpsAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpsAddRequest.Merge(m, src)
}
func (m *CpsAddRequest) XXX_Size() int {
	return xxx_messageInfo_CpsAddRequest.Size(m)
}
func (m *CpsAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CpsAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CpsAddRequest proto.InternalMessageInfo

func (m *CpsAddRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CpsAddRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CpsAddResponse struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpsAddResponse) Reset()         { *m = CpsAddResponse{} }
func (m *CpsAddResponse) String() string { return proto.CompactTextString(m) }
func (*CpsAddResponse) ProtoMessage()    {}
func (*CpsAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ccfebce9e4446d46, []int{16}
}

func (m *CpsAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpsAddResponse.Unmarshal(m, b)
}
func (m *CpsAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpsAddResponse.Marshal(b, m, deterministic)
}
func (m *CpsAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpsAddResponse.Merge(m, src)
}
func (m *CpsAddResponse) XXX_Size() int {
	return xxx_messageInfo_CpsAddResponse.Size(m)
}
func (m *CpsAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CpsAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CpsAddResponse proto.InternalMessageInfo

func (m *CpsAddResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

func init() {
	proto.RegisterType((*GoodsResponse)(nil), "GoodsResponse")
	proto.RegisterType((*GoodsRequest)(nil), "GoodsRequest")
	proto.RegisterType((*ZoneRequest)(nil), "ZoneRequest")
	proto.RegisterType((*ZoneResponse)(nil), "ZoneResponse")
	proto.RegisterType((*Goods)(nil), "goods")
	proto.RegisterType((*Zone)(nil), "zone")
	proto.RegisterType((*ItemResponse)(nil), "ItemResponse")
	proto.RegisterType((*ItemRequest)(nil), "ItemRequest")
	proto.RegisterType((*Item)(nil), "item")
	proto.RegisterType((*User)(nil), "user")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
	proto.RegisterType((*UserRequest)(nil), "UserRequest")
	proto.RegisterType((*ButtonAddRequest)(nil), "ButtonAddRequest")
	proto.RegisterType((*ButtonDelRequest)(nil), "ButtonDelRequest")
	proto.RegisterType((*BoolResponse)(nil), "BoolResponse")
	proto.RegisterType((*CpsAddRequest)(nil), "CpsAddRequest")
	proto.RegisterType((*CpsAddResponse)(nil), "CpsAddResponse")
}

func init() { proto.RegisterFile("child.proto", fileDescriptor_ccfebce9e4446d46) }

var fileDescriptor_ccfebce9e4446d46 = []byte{
	// 486 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x8e, 0x1d, 0x27, 0x34, 0xe3, 0x1f, 0x60, 0x0e, 0x28, 0xb8, 0x15, 0x8a, 0x56, 0x42, 0x4a,
	0xa9, 0xb4, 0x48, 0xad, 0xc4, 0x81, 0x0b, 0xa2, 0xa9, 0x84, 0x72, 0xe1, 0x60, 0xc4, 0x85, 0x9b,
	0xf1, 0xae, 0xc0, 0x4a, 0xea, 0x0d, 0xb6, 0xc3, 0x81, 0x57, 0xe3, 0xe5, 0xd0, 0xec, 0xae, 0x9d,
	0x35, 0x24, 0x12, 0xea, 0xc9, 0x33, 0x3b, 0xf3, 0xcd, 0x37, 0xbf, 0x86, 0xb0, 0xf8, 0x5e, 0x6e,
	0x05, 0xdf, 0xd5, 0xaa, 0x55, 0xec, 0x0a, 0xe2, 0x0f, 0x4a, 0x89, 0x26, 0x93, 0xcd, 0x4e, 0x55,
	0x8d, 0xc4, 0x14, 0x02, 0x91, 0xb7, 0xf9, 0xdc, 0x5b, 0x8c, 0x97, 0xe1, 0xf5, 0x94, 0x7f, 0xd3,
	0x56, 0xfd, 0xc6, 0x2e, 0x20, 0xb2, 0xce, 0x3f, 0xf6, 0xb2, 0x69, 0x31, 0x02, 0x8f, 0x1c, 0xbd,
	0xe5, 0x59, 0xe6, 0xe5, 0xec, 0x1c, 0xc2, 0x2f, 0xaa, 0x92, 0xc7, 0x8d, 0x97, 0x10, 0x19, 0xa3,
	0xa5, 0x79, 0x3e, 0xa0, 0x99, 0xf0, 0x5f, 0x64, 0x34, 0x2c, 0xef, 0x60, 0xa2, 0x49, 0x71, 0x0e,
	0x8f, 0xb4, 0xb0, 0x16, 0x3a, 0xce, 0x24, 0xeb, 0x54, 0xbc, 0x80, 0x99, 0x16, 0x3f, 0xe6, 0xf7,
	0x72, 0xee, 0x2f, 0xbc, 0xe5, 0x2c, 0x3b, 0x3c, 0xb0, 0xb7, 0x10, 0x50, 0x38, 0x7c, 0x06, 0x53,
	0xfa, 0xf6, 0x70, 0xab, 0x61, 0x0a, 0x67, 0x24, 0x39, 0xe0, 0x5e, 0xa7, 0x3c, 0xd7, 0xad, 0xbc,
	0x3f, 0x99, 0x67, 0x49, 0x46, 0x93, 0xe7, 0x39, 0x84, 0xc6, 0xf5, 0x58, 0xbd, 0xaf, 0x20, 0x20,
	0x57, 0x4c, 0xc0, 0x2f, 0x3b, 0x7e, 0xbf, 0x14, 0x88, 0x10, 0x54, 0x07, 0x5e, 0x2d, 0x33, 0x01,
	0xc1, 0xbe, 0x91, 0x35, 0x55, 0x95, 0x17, 0x85, 0xda, 0x57, 0xad, 0x4d, 0x79, 0x9c, 0x1d, 0x1e,
	0xa8, 0x1a, 0xf2, 0x5a, 0x0b, 0x8d, 0x1d, 0x67, 0x56, 0xd3, 0x11, 0xcb, 0x62, 0x33, 0x1f, 0xdb,
	0x88, 0x65, 0xb1, 0xe9, 0x59, 0x02, 0x87, 0xe5, 0x12, 0xa2, 0xcf, 0x8d, 0xac, 0x8f, 0x54, 0xe6,
	0xe9, 0xca, 0x28, 0x9c, 0xad, 0x6c, 0x05, 0xa1, 0x71, 0x35, 0x95, 0x3d, 0x28, 0x2f, 0xf6, 0x06,
	0x9e, 0xdc, 0xee, 0xdb, 0x56, 0x55, 0xef, 0x85, 0xe8, 0x22, 0xfd, 0x4f, 0x37, 0x58, 0x87, 0xbb,
	0x93, 0xdb, 0x13, 0x38, 0xf6, 0x02, 0xa2, 0x5b, 0xa5, 0xb6, 0x7d, 0x2d, 0x09, 0xf8, 0x6a, 0x63,
	0x9b, 0xef, 0xab, 0x0d, 0xbb, 0x81, 0x78, 0xb5, 0x6b, 0x86, 0xc4, 0xfd, 0x1a, 0xf8, 0xa6, 0x69,
	0xce, 0xf8, 0xb5, 0xcc, 0x16, 0x90, 0x74, 0xa0, 0xe3, 0x61, 0xaf, 0x7f, 0xfb, 0x10, 0xae, 0xe8,
	0x78, 0x3e, 0xc9, 0xfa, 0xa7, 0xac, 0x71, 0x09, 0x13, 0x7d, 0x0f, 0x18, 0x73, 0xf7, 0x2e, 0xd2,
	0x84, 0x0f, 0x6e, 0x8a, 0x8d, 0xf0, 0x25, 0x04, 0xb4, 0xfe, 0x18, 0x71, 0xe7, 0x44, 0xd2, 0x98,
	0xbb, 0x37, 0x61, 0xdc, 0x68, 0xa5, 0x30, 0xe2, 0xce, 0x66, 0xa5, 0x31, 0x77, 0x57, 0xd2, 0xb8,
	0xd1, 0x7c, 0x30, 0xe2, 0xce, 0x98, 0xd2, 0x98, 0xbb, 0xf3, 0x65, 0x23, 0x7c, 0x0d, 0xb3, 0x7e,
	0x02, 0xf8, 0x94, 0xff, 0x3d, 0x8d, 0x34, 0xe6, 0x6e, 0x13, 0x5d, 0xc0, 0x9d, 0xdc, 0xf6, 0x80,
	0xc3, 0x18, 0xfe, 0x05, 0x5c, 0xc1, 0xd4, 0xb4, 0x0c, 0x13, 0x3e, 0x68, 0x78, 0xfa, 0x98, 0x0f,
	0x7b, 0xc9, 0x46, 0x5f, 0xa7, 0xfa, 0x8f, 0x73, 0xf3, 0x27, 0x00, 0x00, 0xff, 0xff, 0x08, 0x09,
	0x0a, 0x18, 0x80, 0x04, 0x00, 0x00,
}
