// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pf.proto

package proto_server

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CpsRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminId              int32    `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpsRequest) Reset()         { *m = CpsRequest{} }
func (m *CpsRequest) String() string { return proto.CompactTextString(m) }
func (*CpsRequest) ProtoMessage()    {}
func (*CpsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{0}
}

func (m *CpsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpsRequest.Unmarshal(m, b)
}
func (m *CpsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpsRequest.Marshal(b, m, deterministic)
}
func (m *CpsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpsRequest.Merge(m, src)
}
func (m *CpsRequest) XXX_Size() int {
	return xxx_messageInfo_CpsRequest.Size(m)
}
func (m *CpsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CpsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CpsRequest proto.InternalMessageInfo

func (m *CpsRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *CpsRequest) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type CpsResponse struct {
	Data                 []*Cps   `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CpsResponse) Reset()         { *m = CpsResponse{} }
func (m *CpsResponse) String() string { return proto.CompactTextString(m) }
func (*CpsResponse) ProtoMessage()    {}
func (*CpsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{1}
}

func (m *CpsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CpsResponse.Unmarshal(m, b)
}
func (m *CpsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CpsResponse.Marshal(b, m, deterministic)
}
func (m *CpsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CpsResponse.Merge(m, src)
}
func (m *CpsResponse) XXX_Size() int {
	return xxx_messageInfo_CpsResponse.Size(m)
}
func (m *CpsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CpsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CpsResponse proto.InternalMessageInfo

func (m *CpsResponse) GetData() []*Cps {
	if m != nil {
		return m.Data
	}
	return nil
}

type GoodsUpdateResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsUpdateResponse) Reset()         { *m = GoodsUpdateResponse{} }
func (m *GoodsUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsUpdateResponse) ProtoMessage()    {}
func (*GoodsUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{2}
}

func (m *GoodsUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsUpdateResponse.Unmarshal(m, b)
}
func (m *GoodsUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsUpdateResponse.Marshal(b, m, deterministic)
}
func (m *GoodsUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsUpdateResponse.Merge(m, src)
}
func (m *GoodsUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsUpdateResponse.Size(m)
}
func (m *GoodsUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsUpdateResponse proto.InternalMessageInfo

func (m *GoodsUpdateResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type GoodsDelResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsDelResponse) Reset()         { *m = GoodsDelResponse{} }
func (m *GoodsDelResponse) String() string { return proto.CompactTextString(m) }
func (*GoodsDelResponse) ProtoMessage()    {}
func (*GoodsDelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{3}
}

func (m *GoodsDelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsDelResponse.Unmarshal(m, b)
}
func (m *GoodsDelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsDelResponse.Marshal(b, m, deterministic)
}
func (m *GoodsDelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsDelResponse.Merge(m, src)
}
func (m *GoodsDelResponse) XXX_Size() int {
	return xxx_messageInfo_GoodsDelResponse.Size(m)
}
func (m *GoodsDelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsDelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsDelResponse proto.InternalMessageInfo

func (m *GoodsDelResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type OwnChargeResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnChargeResponse) Reset()         { *m = OwnChargeResponse{} }
func (m *OwnChargeResponse) String() string { return proto.CompactTextString(m) }
func (*OwnChargeResponse) ProtoMessage()    {}
func (*OwnChargeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{4}
}

func (m *OwnChargeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnChargeResponse.Unmarshal(m, b)
}
func (m *OwnChargeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnChargeResponse.Marshal(b, m, deterministic)
}
func (m *OwnChargeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnChargeResponse.Merge(m, src)
}
func (m *OwnChargeResponse) XXX_Size() int {
	return xxx_messageInfo_OwnChargeResponse.Size(m)
}
func (m *OwnChargeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnChargeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OwnChargeResponse proto.InternalMessageInfo

func (m *OwnChargeResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type Cps struct {
	Id                   int32    `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Cps) Reset()         { *m = Cps{} }
func (m *Cps) String() string { return proto.CompactTextString(m) }
func (*Cps) ProtoMessage()    {}
func (*Cps) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{5}
}

func (m *Cps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Cps.Unmarshal(m, b)
}
func (m *Cps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Cps.Marshal(b, m, deterministic)
}
func (m *Cps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Cps.Merge(m, src)
}
func (m *Cps) XXX_Size() int {
	return xxx_messageInfo_Cps.Size(m)
}
func (m *Cps) XXX_DiscardUnknown() {
	xxx_messageInfo_Cps.DiscardUnknown(m)
}

var xxx_messageInfo_Cps proto.InternalMessageInfo

func (m *Cps) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Cps) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GameRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminId              int32    `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameRequest) Reset()         { *m = GameRequest{} }
func (m *GameRequest) String() string { return proto.CompactTextString(m) }
func (*GameRequest) ProtoMessage()    {}
func (*GameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{6}
}

func (m *GameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameRequest.Unmarshal(m, b)
}
func (m *GameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameRequest.Marshal(b, m, deterministic)
}
func (m *GameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameRequest.Merge(m, src)
}
func (m *GameRequest) XXX_Size() int {
	return xxx_messageInfo_GameRequest.Size(m)
}
func (m *GameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GameRequest proto.InternalMessageInfo

func (m *GameRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GameRequest) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

type GameResponse struct {
	AppKey               string   `protobuf:"bytes,1,opt,name=appKey,proto3" json:"appKey,omitempty"`
	AppSecret            string   `protobuf:"bytes,2,opt,name=appSecret,proto3" json:"appSecret,omitempty"`
	GameName             string   `protobuf:"bytes,3,opt,name=gameName,proto3" json:"gameName,omitempty"`
	GameId               int32    `protobuf:"varint,4,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{7}
}

func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (m *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(m, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetAppKey() string {
	if m != nil {
		return m.AppKey
	}
	return ""
}

func (m *GameResponse) GetAppSecret() string {
	if m != nil {
		return m.AppSecret
	}
	return ""
}

func (m *GameResponse) GetGameName() string {
	if m != nil {
		return m.GameName
	}
	return ""
}

func (m *GameResponse) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type GoodsAddRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminId              int32    `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	Price                int32    `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	LimitNum             int32    `protobuf:"varint,6,opt,name=limitNum,proto3" json:"limitNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsAddRequest) Reset()         { *m = GoodsAddRequest{} }
func (m *GoodsAddRequest) String() string { return proto.CompactTextString(m) }
func (*GoodsAddRequest) ProtoMessage()    {}
func (*GoodsAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{8}
}

func (m *GoodsAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsAddRequest.Unmarshal(m, b)
}
func (m *GoodsAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsAddRequest.Marshal(b, m, deterministic)
}
func (m *GoodsAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsAddRequest.Merge(m, src)
}
func (m *GoodsAddRequest) XXX_Size() int {
	return xxx_messageInfo_GoodsAddRequest.Size(m)
}
func (m *GoodsAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsAddRequest proto.InternalMessageInfo

func (m *GoodsAddRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GoodsAddRequest) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *GoodsAddRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *GoodsAddRequest) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *GoodsAddRequest) GetPrice() int32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *GoodsAddRequest) GetLimitNum() int32 {
	if m != nil {
		return m.LimitNum
	}
	return 0
}

type GoodsDelRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminId              int32    `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsDelRequest) Reset()         { *m = GoodsDelRequest{} }
func (m *GoodsDelRequest) String() string { return proto.CompactTextString(m) }
func (*GoodsDelRequest) ProtoMessage()    {}
func (*GoodsDelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{9}
}

func (m *GoodsDelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsDelRequest.Unmarshal(m, b)
}
func (m *GoodsDelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsDelRequest.Marshal(b, m, deterministic)
}
func (m *GoodsDelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsDelRequest.Merge(m, src)
}
func (m *GoodsDelRequest) XXX_Size() int {
	return xxx_messageInfo_GoodsDelRequest.Size(m)
}
func (m *GoodsDelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsDelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsDelRequest proto.InternalMessageInfo

func (m *GoodsDelRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *GoodsDelRequest) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *GoodsDelRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type OwnChargeRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	AdminId              int32    `protobuf:"varint,2,opt,name=adminId,proto3" json:"adminId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	ZoneId               string   `protobuf:"bytes,5,opt,name=zoneId,proto3" json:"zoneId,omitempty"`
	AccountId            int64    `protobuf:"varint,6,opt,name=accountId,proto3" json:"accountId,omitempty"`
	UserId               int64    `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	AdminName            string   `protobuf:"bytes,8,opt,name=adminName,proto3" json:"adminName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OwnChargeRequest) Reset()         { *m = OwnChargeRequest{} }
func (m *OwnChargeRequest) String() string { return proto.CompactTextString(m) }
func (*OwnChargeRequest) ProtoMessage()    {}
func (*OwnChargeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{10}
}

func (m *OwnChargeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OwnChargeRequest.Unmarshal(m, b)
}
func (m *OwnChargeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OwnChargeRequest.Marshal(b, m, deterministic)
}
func (m *OwnChargeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OwnChargeRequest.Merge(m, src)
}
func (m *OwnChargeRequest) XXX_Size() int {
	return xxx_messageInfo_OwnChargeRequest.Size(m)
}
func (m *OwnChargeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OwnChargeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OwnChargeRequest proto.InternalMessageInfo

func (m *OwnChargeRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *OwnChargeRequest) GetAdminId() int32 {
	if m != nil {
		return m.AdminId
	}
	return 0
}

func (m *OwnChargeRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *OwnChargeRequest) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *OwnChargeRequest) GetZoneId() string {
	if m != nil {
		return m.ZoneId
	}
	return ""
}

func (m *OwnChargeRequest) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *OwnChargeRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OwnChargeRequest) GetAdminName() string {
	if m != nil {
		return m.AdminName
	}
	return ""
}

type ItemAddRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	ItemId               int32    `protobuf:"varint,2,opt,name=itemId,proto3" json:"itemId,omitempty"`
	ItemName             string   `protobuf:"bytes,3,opt,name=itemName,proto3" json:"itemName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemAddRequest) Reset()         { *m = ItemAddRequest{} }
func (m *ItemAddRequest) String() string { return proto.CompactTextString(m) }
func (*ItemAddRequest) ProtoMessage()    {}
func (*ItemAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{11}
}

func (m *ItemAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAddRequest.Unmarshal(m, b)
}
func (m *ItemAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAddRequest.Marshal(b, m, deterministic)
}
func (m *ItemAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAddRequest.Merge(m, src)
}
func (m *ItemAddRequest) XXX_Size() int {
	return xxx_messageInfo_ItemAddRequest.Size(m)
}
func (m *ItemAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAddRequest proto.InternalMessageInfo

func (m *ItemAddRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *ItemAddRequest) GetItemId() int32 {
	if m != nil {
		return m.ItemId
	}
	return 0
}

func (m *ItemAddRequest) GetItemName() string {
	if m != nil {
		return m.ItemName
	}
	return ""
}

type ItemAddResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ItemAddResponse) Reset()         { *m = ItemAddResponse{} }
func (m *ItemAddResponse) String() string { return proto.CompactTextString(m) }
func (*ItemAddResponse) ProtoMessage()    {}
func (*ItemAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{12}
}

func (m *ItemAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ItemAddResponse.Unmarshal(m, b)
}
func (m *ItemAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ItemAddResponse.Marshal(b, m, deterministic)
}
func (m *ItemAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ItemAddResponse.Merge(m, src)
}
func (m *ItemAddResponse) XXX_Size() int {
	return xxx_messageInfo_ItemAddResponse.Size(m)
}
func (m *ItemAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ItemAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ItemAddResponse proto.InternalMessageInfo

func (m *ItemAddResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type ZoneAddRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Zid                  string   `protobuf:"bytes,2,opt,name=zid,proto3" json:"zid,omitempty"`
	ZName                string   `protobuf:"bytes,3,opt,name=zName,proto3" json:"zName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneAddRequest) Reset()         { *m = ZoneAddRequest{} }
func (m *ZoneAddRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneAddRequest) ProtoMessage()    {}
func (*ZoneAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{13}
}

func (m *ZoneAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneAddRequest.Unmarshal(m, b)
}
func (m *ZoneAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneAddRequest.Marshal(b, m, deterministic)
}
func (m *ZoneAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneAddRequest.Merge(m, src)
}
func (m *ZoneAddRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneAddRequest.Size(m)
}
func (m *ZoneAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneAddRequest proto.InternalMessageInfo

func (m *ZoneAddRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *ZoneAddRequest) GetZid() string {
	if m != nil {
		return m.Zid
	}
	return ""
}

func (m *ZoneAddRequest) GetZName() string {
	if m != nil {
		return m.ZName
	}
	return ""
}

type ZoneAddResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneAddResponse) Reset()         { *m = ZoneAddResponse{} }
func (m *ZoneAddResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneAddResponse) ProtoMessage()    {}
func (*ZoneAddResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{14}
}

func (m *ZoneAddResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneAddResponse.Unmarshal(m, b)
}
func (m *ZoneAddResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneAddResponse.Marshal(b, m, deterministic)
}
func (m *ZoneAddResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneAddResponse.Merge(m, src)
}
func (m *ZoneAddResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneAddResponse.Size(m)
}
func (m *ZoneAddResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneAddResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneAddResponse proto.InternalMessageInfo

func (m *ZoneAddResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type ZoneDelRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	Zid                  string   `protobuf:"bytes,2,opt,name=zid,proto3" json:"zid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneDelRequest) Reset()         { *m = ZoneDelRequest{} }
func (m *ZoneDelRequest) String() string { return proto.CompactTextString(m) }
func (*ZoneDelRequest) ProtoMessage()    {}
func (*ZoneDelRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{15}
}

func (m *ZoneDelRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneDelRequest.Unmarshal(m, b)
}
func (m *ZoneDelRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneDelRequest.Marshal(b, m, deterministic)
}
func (m *ZoneDelRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneDelRequest.Merge(m, src)
}
func (m *ZoneDelRequest) XXX_Size() int {
	return xxx_messageInfo_ZoneDelRequest.Size(m)
}
func (m *ZoneDelRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneDelRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneDelRequest proto.InternalMessageInfo

func (m *ZoneDelRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *ZoneDelRequest) GetZid() string {
	if m != nil {
		return m.Zid
	}
	return ""
}

type ZoneDelResponse struct {
	A                    bool     `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ZoneDelResponse) Reset()         { *m = ZoneDelResponse{} }
func (m *ZoneDelResponse) String() string { return proto.CompactTextString(m) }
func (*ZoneDelResponse) ProtoMessage()    {}
func (*ZoneDelResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{16}
}

func (m *ZoneDelResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ZoneDelResponse.Unmarshal(m, b)
}
func (m *ZoneDelResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ZoneDelResponse.Marshal(b, m, deterministic)
}
func (m *ZoneDelResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ZoneDelResponse.Merge(m, src)
}
func (m *ZoneDelResponse) XXX_Size() int {
	return xxx_messageInfo_ZoneDelResponse.Size(m)
}
func (m *ZoneDelResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ZoneDelResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ZoneDelResponse proto.InternalMessageInfo

func (m *ZoneDelResponse) GetA() bool {
	if m != nil {
		return m.A
	}
	return false
}

type ButtonRequest struct {
	GameId               int32    `protobuf:"varint,1,opt,name=gameId,proto3" json:"gameId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ButtonRequest) Reset()         { *m = ButtonRequest{} }
func (m *ButtonRequest) String() string { return proto.CompactTextString(m) }
func (*ButtonRequest) ProtoMessage()    {}
func (*ButtonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{17}
}

func (m *ButtonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ButtonRequest.Unmarshal(m, b)
}
func (m *ButtonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ButtonRequest.Marshal(b, m, deterministic)
}
func (m *ButtonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ButtonRequest.Merge(m, src)
}
func (m *ButtonRequest) XXX_Size() int {
	return xxx_messageInfo_ButtonRequest.Size(m)
}
func (m *ButtonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ButtonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ButtonRequest proto.InternalMessageInfo

func (m *ButtonRequest) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

type Button struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Button) Reset()         { *m = Button{} }
func (m *Button) String() string { return proto.CompactTextString(m) }
func (*Button) ProtoMessage()    {}
func (*Button) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{18}
}

func (m *Button) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Button.Unmarshal(m, b)
}
func (m *Button) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Button.Marshal(b, m, deterministic)
}
func (m *Button) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Button.Merge(m, src)
}
func (m *Button) XXX_Size() int {
	return xxx_messageInfo_Button.Size(m)
}
func (m *Button) XXX_DiscardUnknown() {
	xxx_messageInfo_Button.DiscardUnknown(m)
}

var xxx_messageInfo_Button proto.InternalMessageInfo

func (m *Button) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Button) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ButtonResponse struct {
	Data                 []*Button `protobuf:"bytes,1,rep,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ButtonResponse) Reset()         { *m = ButtonResponse{} }
func (m *ButtonResponse) String() string { return proto.CompactTextString(m) }
func (*ButtonResponse) ProtoMessage()    {}
func (*ButtonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ed56b398dbf4e79, []int{19}
}

func (m *ButtonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ButtonResponse.Unmarshal(m, b)
}
func (m *ButtonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ButtonResponse.Marshal(b, m, deterministic)
}
func (m *ButtonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ButtonResponse.Merge(m, src)
}
func (m *ButtonResponse) XXX_Size() int {
	return xxx_messageInfo_ButtonResponse.Size(m)
}
func (m *ButtonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ButtonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ButtonResponse proto.InternalMessageInfo

func (m *ButtonResponse) GetData() []*Button {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CpsRequest)(nil), "CpsRequest")
	proto.RegisterType((*CpsResponse)(nil), "CpsResponse")
	proto.RegisterType((*GoodsUpdateResponse)(nil), "GoodsUpdateResponse")
	proto.RegisterType((*GoodsDelResponse)(nil), "GoodsDelResponse")
	proto.RegisterType((*OwnChargeResponse)(nil), "OwnChargeResponse")
	proto.RegisterType((*Cps)(nil), "Cps")
	proto.RegisterType((*GameRequest)(nil), "GameRequest")
	proto.RegisterType((*GameResponse)(nil), "GameResponse")
	proto.RegisterType((*GoodsAddRequest)(nil), "GoodsAddRequest")
	proto.RegisterType((*GoodsDelRequest)(nil), "GoodsDelRequest")
	proto.RegisterType((*OwnChargeRequest)(nil), "OwnChargeRequest")
	proto.RegisterType((*ItemAddRequest)(nil), "ItemAddRequest")
	proto.RegisterType((*ItemAddResponse)(nil), "ItemAddResponse")
	proto.RegisterType((*ZoneAddRequest)(nil), "ZoneAddRequest")
	proto.RegisterType((*ZoneAddResponse)(nil), "ZoneAddResponse")
	proto.RegisterType((*ZoneDelRequest)(nil), "ZoneDelRequest")
	proto.RegisterType((*ZoneDelResponse)(nil), "ZoneDelResponse")
	proto.RegisterType((*ButtonRequest)(nil), "ButtonRequest")
	proto.RegisterType((*Button)(nil), "button")
	proto.RegisterType((*ButtonResponse)(nil), "ButtonResponse")
}

func init() { proto.RegisterFile("pf.proto", fileDescriptor_6ed56b398dbf4e79) }

var fileDescriptor_6ed56b398dbf4e79 = []byte{
	// 667 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0x5f, 0x6b, 0xd4, 0x4e,
	0x14, 0x4d, 0x9a, 0x6c, 0x76, 0xf7, 0xee, 0x76, 0x37, 0x9d, 0x5f, 0x59, 0x42, 0x7e, 0x82, 0x75,
	0x44, 0x5a, 0x51, 0x07, 0xac, 0x82, 0xe0, 0x83, 0xd2, 0x3f, 0x50, 0x82, 0x50, 0x4b, 0xc4, 0x17,
	0xd1, 0x87, 0xe9, 0xce, 0xb4, 0x06, 0x9a, 0x3f, 0x6e, 0xb2, 0xa8, 0xfd, 0x4e, 0xfd, 0x5e, 0x7e,
	0x0c, 0x99, 0x9b, 0x49, 0x36, 0x9b, 0xb6, 0xb8, 0x14, 0xf1, 0x6d, 0xce, 0xdc, 0xb9, 0xf7, 0x9c,
	0xc9, 0xbd, 0x73, 0x02, 0xbd, 0xec, 0x8c, 0x65, 0xb3, 0xb4, 0x48, 0xe9, 0x1b, 0x80, 0x83, 0x2c,
	0x0f, 0xe5, 0xb7, 0xb9, 0xcc, 0x0b, 0x32, 0x01, 0xe7, 0x9c, 0xc7, 0x32, 0x10, 0x9e, 0xb9, 0x65,
	0xee, 0x74, 0x42, 0x8d, 0x88, 0x07, 0x5d, 0x2e, 0xe2, 0x28, 0x09, 0x84, 0xb7, 0x86, 0x81, 0x0a,
	0xd2, 0x6d, 0x18, 0x60, 0x7e, 0x9e, 0xa5, 0x49, 0x2e, 0x89, 0x07, 0xf6, 0x21, 0x2f, 0xb8, 0x67,
	0x6e, 0x59, 0x3b, 0x83, 0x5d, 0x9b, 0xa9, 0x18, 0xee, 0xd0, 0x87, 0xf0, 0xdf, 0x51, 0x9a, 0x8a,
	0xfc, 0x63, 0x26, 0x78, 0x21, 0xeb, 0x84, 0x21, 0x98, 0x1c, 0xc9, 0x7a, 0xa1, 0xc9, 0xe9, 0x16,
	0xb8, 0x78, 0xe8, 0x50, 0x5e, 0xdc, 0x72, 0xe2, 0x01, 0x6c, 0xbc, 0xff, 0x9e, 0x1c, 0x7c, 0xe5,
	0xb3, 0xf3, 0xdb, 0x8a, 0x3c, 0x06, 0xeb, 0x20, 0xcb, 0xc9, 0x08, 0xd6, 0xea, 0x7b, 0xac, 0x05,
	0x82, 0x10, 0xb0, 0x8f, 0x79, 0x2c, 0xf1, 0x02, 0xfd, 0x10, 0xd7, 0xf4, 0x2d, 0x0c, 0x8e, 0x78,
	0x2c, 0xef, 0x7e, 0xfd, 0x1f, 0x30, 0x2c, 0x0b, 0x68, 0x25, 0x13, 0x70, 0x78, 0x96, 0xbd, 0x93,
	0x3f, 0xb1, 0x42, 0x3f, 0xd4, 0x88, 0xdc, 0x83, 0x3e, 0xcf, 0xb2, 0x0f, 0x72, 0x3a, 0x93, 0x85,
	0x56, 0xb0, 0xd8, 0x20, 0x3e, 0xf4, 0x14, 0x13, 0xca, 0xb3, 0x30, 0x58, 0xe3, 0x86, 0x26, 0xbb,
	0xa9, 0x89, 0x5e, 0x99, 0x30, 0xc6, 0x6f, 0xb5, 0x27, 0xc4, 0x9d, 0xf5, 0xab, 0xc8, 0xb9, 0x2a,
	0x12, 0x08, 0x24, 0xee, 0x84, 0x15, 0x54, 0x8a, 0x71, 0x89, 0xa2, 0xec, 0x52, 0x71, 0xbd, 0x41,
	0x36, 0xa1, 0x93, 0xcd, 0xa2, 0xa9, 0xf4, 0x3a, 0x98, 0x55, 0x02, 0x75, 0x8f, 0x8b, 0x28, 0x8e,
	0x8a, 0xe3, 0x79, 0xec, 0x39, 0x18, 0xa8, 0x31, 0xfd, 0xa2, 0xe5, 0x62, 0x6b, 0xff, 0xba, 0x5c,
	0xfa, 0xcb, 0x04, 0xb7, 0x31, 0x18, 0xff, 0xfa, 0x7b, 0x4c, 0xc0, 0xb9, 0x4c, 0x13, 0xc5, 0xd4,
	0x29, 0xfb, 0x5e, 0x22, 0xec, 0xfb, 0x74, 0x9a, 0xce, 0x93, 0x22, 0x10, 0xf8, 0x49, 0xac, 0x70,
	0xb1, 0xa1, 0xb2, 0xe6, 0xb9, 0x9c, 0x05, 0xc2, 0xeb, 0x62, 0x48, 0x23, 0xcc, 0x52, 0x82, 0x90,
	0xab, 0xa7, 0xa7, 0xa5, 0xda, 0xa0, 0x9f, 0x61, 0x14, 0x14, 0x32, 0x5e, 0xa1, 0xef, 0x13, 0x70,
	0xa2, 0x42, 0xc6, 0xf5, 0x35, 0x35, 0x52, 0x7d, 0x52, 0xab, 0xe6, 0xbc, 0x55, 0x98, 0xde, 0x87,
	0x71, 0x5d, 0xfd, 0xc6, 0xe7, 0x75, 0x02, 0xa3, 0x4f, 0x69, 0x22, 0x57, 0xa0, 0x77, 0xc1, 0xba,
	0x8c, 0x84, 0x1e, 0x77, 0xb5, 0x54, 0x63, 0x73, 0xd9, 0x60, 0x2d, 0x81, 0xa2, 0xac, 0x2b, 0xde,
	0x48, 0xf9, 0xba, 0xa4, 0x5c, 0x61, 0x74, 0xae, 0x51, 0x56, 0xc5, 0x6f, 0x77, 0x94, 0x6d, 0x58,
	0xdf, 0x9f, 0x17, 0x45, 0x9a, 0xfc, 0xa1, 0x36, 0x7d, 0x0a, 0xce, 0x29, 0x1e, 0x54, 0xd6, 0x12,
	0xd5, 0xd6, 0x12, 0xa1, 0xb5, 0x24, 0x0d, 0x6b, 0x51, 0x6b, 0xfa, 0x0c, 0x46, 0x55, 0x59, 0x4d,
	0xfb, 0xff, 0x92, 0x37, 0x76, 0x59, 0x59, 0xac, 0xb4, 0xc7, 0xdd, 0x2b, 0x0b, 0xba, 0x27, 0x67,
	0x7b, 0xaa, 0xc9, 0x84, 0x96, 0x06, 0x36, 0x60, 0x0b, 0x67, 0xf6, 0x87, 0xac, 0x61, 0xb3, 0xd4,
	0x20, 0x8f, 0xc0, 0x56, 0xc6, 0x43, 0x86, 0xac, 0x61, 0x60, 0xfe, 0x3a, 0x6b, 0xba, 0x11, 0x35,
	0xc8, 0x2b, 0x18, 0x34, 0x5c, 0x97, 0xb8, 0xac, 0x65, 0x19, 0xfe, 0x26, 0xbb, 0xc1, 0x95, 0xa9,
	0x41, 0x9e, 0x43, 0xaf, 0x7a, 0xae, 0x55, 0xd6, 0xe2, 0xf3, 0xfb, 0x1b, 0xac, 0x6d, 0xd3, 0xd4,
	0x20, 0x2f, 0xa1, 0x5f, 0xbf, 0x40, 0xb2, 0xc1, 0xda, 0xaf, 0xd1, 0x27, 0xec, 0x9a, 0x73, 0x53,
	0x83, 0x3c, 0x01, 0x5b, 0xf5, 0x87, 0x8c, 0xd9, 0xf2, 0x54, 0xf9, 0x2e, 0x6b, 0x0d, 0x05, 0x35,
	0x08, 0x83, 0xae, 0x6e, 0xa6, 0x3e, 0xdf, 0xd0, 0xe4, 0xb2, 0x56, 0x9f, 0xcb, 0xe2, 0x6a, 0x98,
	0xc9, 0x98, 0x2d, 0xbf, 0x18, 0xdf, 0x65, 0xad, 0x21, 0xc7, 0xc3, 0xce, 0xbe, 0xee, 0x2f, 0x5b,
	0x9a, 0x08, 0x7f, 0xcc, 0x96, 0x5b, 0x49, 0x8d, 0x53, 0x07, 0x7f, 0x9f, 0x2f, 0x7e, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xea, 0x4c, 0xb6, 0x8c, 0x4a, 0x07, 0x00, 0x00,
}
